service: cipherService # NOTE: update this with your service name
frameworkVersion: ">=1.28.0 <2.0.0"
provider:
  name: aws
  runtime: go1.x

layers:
  cipherLayer:
    path: bin/plugin
    compatibleRuntimes:
      - go1.x

functions:
  engine:
    handler: bin/cipherEngine
    package:
      exclude:
        - ./**
      include:
        - ./bin/cipherEngine
    layers:
      - {Ref: CipherLayerLambdaLayer }
